DROP TABLE SERVICE_FIX_DETAILS;
  CREATE TABLE SERVICE_FIX_DETAILS
   (	"ENTITY_NAME" NUMBER(10,0), 
	"TABNAME" VARCHAR2(40 BYTE), 
	"KEYNAME" VARCHAR2(40 BYTE), 
	"SEQ_NUM" NUMBER(3,0), 
	"ISACTIVE" VARCHAR2(1 BYTE), 
	"OPERATION_MODE" VARCHAR2(40 BYTE), 
	"TYPEOFATTRIBUTE" VARCHAR2(100 BYTE), 
	"ACTION_BUTTON" VARCHAR2(1000 BYTE), 
	"AFTER_AC_BU_FRAME" VARCHAR2(100 BYTE), 
	"BEFORE_AC_BU_FRAME" VARCHAR2(100 BYTE), 
	"ELEMENTTYPE" VARCHAR2(20 BYTE)
   ) ;
  
